networks:
  default:
    driver: bridge
    name: roboshop

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  mongodb: 
    image: gsurendhar/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: gsurendhar/catalogue:v2
    container_name: catalogue
    environment:
      MONGO: "true" 
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis 
    volumes:
    - redis:/data  
  user:
    image: gsurendhar/user:v2
    container_name: user
    environment:
      MONGO: "true" 
      REDIS_URL: "redis://redis:6379"
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - mongodb
    - redis
  cart:
    image: gsurendhar/cart:v2
    container_name: cart
    environment:
      REDIS_HOST: "redis"
      CATALOGUE_HOST: "catalogue"
      CATALOGUE_PORT: "8080"
    depends_on:
    - catalogue
    - redis
  mysql:
    image: gsurendhar/mysql:v1
    container_name: mysql
    volumes: 
    - mysql:/var/lib/mysql
  shipping: 
    image: gsurendhar/shipping:v2
    container_name: shipping
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: "mysql"
    depends_on:
    - mysql
    - cart
  rabbitmq: 
    image: gsurendhar/rabbitmq:v1
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  payment:
    image: gsurendhar/payment:v2
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: gsurendhar/frontend:v2
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment